Autodesk/cloud-compute-cannon

bin/cli-test, bin/stack-noserver, etc/hxml/cli-build.hxml, src/haxe/ccc/compute/ComputeQueue.hx, src/haxe/ccc/compute/Definitions.hx, src/haxe/ccc/compute/JobTools.hx, src/haxe/ccc/compute/ServiceBatchCompute.hx, src/haxe/ccc/compute/cli/CliMain.hx, src/haxe/ccc/compute/cli/ClientCommands.hx, src/haxe/ccc/compute/client/ClientCompute.hx, src/haxe/ccc/compute/execution/BatchComputeDocker.hx, src/haxe/ccc/compute/execution/DockerJobTools.hx, src/haxe/ccc/compute/execution/Job.hx, src/haxe/promhx/RedisPromises.hx
- Catch error from timeouts if the docker image cannot be downloaded.
- Also do not give stdout/err paths for finished jobs if the files do not exist.
=> BBLL-178 server crash

docker-compose.override.yml
- Enforce json-file logging in case the remote server has a different default
=> Enforce json-file logging

src/haxe/promhx/PromiseQueue.hx
- If the promise returned from the generator function is null, create one.
=> Null check in the PromiseQueue

etc/hxml/base-nodejs.hxml, etc/hxml/base.hxml, src/haxe/AbstractLogger.hx, src/haxe/ccc/compute/Constants.hx, src/haxe/ccc/compute/InstancePool.hx, src/haxe/ccc/compute/JobWebSocket.hx, src/haxe/ccc/compute/ServiceBatchCompute.hx, src/haxe/ccc/compute/client/ClientCompute.hx, src/haxe/ccc/compute/client/ClientTools.hx, src/haxe/ccc/compute/client/cli/ClientCommands.hx, src/haxe/ccc/compute/execution/BatchComputeDocker.hx, src/haxe/ccc/compute/execution/DockerJobTools.hx, src/haxe/ccc/compute/import.hx, src/haxe/ccc/compute/server/ProviderTools.hx, src/haxe/ccc/compute/server/ServerCommands.hx, src/haxe/ccc/compute/server/ServerCompute.hx, src/haxe/ccc/compute/server/tests/ServerCI.hx, src/haxe/ccc/compute/server/tests/ServerTestTools.hx, src/haxe/ccc/compute/server/tests/ServiceTests.hx, src/haxe/ccc/compute/server/tests/TestJobs.hx, src/haxe/ccc/compute/server/tests/TestRegistry.hx, src/haxe/ccc/compute/server/tests/TestServerAPI.hx, src/haxe/promhx/PromiseTools.hx, src/haxe/promhx/RequestPromises.hx, test/src/TestsIntegration.hx, test/src/compute/TestDockerCompute.hx, test/testbase.hxml
Add packaged tests within the server, callable via http. This allows faster and more convenient functional checking.
=> Add packaged tests within the server, callable via http.

bin/run-stack-remote, bin/sync-to-remote, src/haxe/ccc/compute/Definitions.hx, src/haxe/ccc/compute/ServiceBatchCompute.hx, src/haxe/ccc/compute/client/ProxyTools.hx, src/haxe/ccc/compute/client/cli/CliMain.hx, src/haxe/ccc/compute/client/cli/CliTools.hx, src/haxe/ccc/compute/client/cli/ClientCommands.hx, src/haxe/ccc/compute/server/ServerCommands.hx, src/haxe/ccc/compute/server/ServerCompute.hx, src/haxe/ccc/compute/server/tests/ServiceTests.hx, test/src/utils/TestMiscUnit.hx
- Fix broken CLI 
- add version checks, optionally checking for version matching with every call
=> Fix CLI and add version checks

src/haxe/ccc/compute/client/cli/ClientCommands.hx, src/haxe/ccc/compute/execution/DockerJobTools.hx, src/haxe/ccc/compute/server/ProviderTools.hx, src/haxe/ccc/compute/server/ServerCompute.hx, src/haxe/promhx/PromiseTools.hx
- Fixed remote servers using the given non-default config
=> Fix remote server start

bin/run-stack-prod, docker-compose.core.yml, docker-compose.override.yml, docker-compose.prod.yml, etc/server/start.sh, package.json, src/haxe/ccc/compute/Constants.hx, src/haxe/ccc/compute/client/cli/CliTools.hx, src/haxe/ccc/compute/client/cli/ClientCommands.hx, src/haxe/ccc/compute/server/ProviderTools.hx, src/haxe/ccc/compute/server/ServerCompute.hx
- Fixed fluent logging on remote deployment
- Fixed local server issues
=> Fixed remote and local deployment issues

src/haxe/ccc/compute/client/cli/CliMain.hx, src/haxe/ccc/compute/client/cli/CliTools.hx, src/haxe/ccc/compute/client/cli/ClientCommands.hx
FIX:
- CLI would hang on unknown commands
- Some CLI server commands failed for local installs
=> Fix CLI for local installs

bin/run-stack-noserver, src/haxe/ccc/compute/ComputeQueue.hx, src/haxe/ccc/compute/Definitions.hx, src/haxe/ccc/compute/ServiceBatchCompute.hx, src/haxe/ccc/compute/ServiceBatchComputeTools.hx, src/haxe/ccc/compute/server/ServerCommands.hx, src/haxe/ccc/compute/server/ServerCompute.hx, src/haxe/util/RedisTools.hx
"ccc job status" now returns a map (jobId=>status)
=> CLI API: job status

etc/hxml/base.hxml, etc/hxml/cli-build.hxml, src/haxe/AbstractLogger.hx, src/haxe/ccc/compute/ServiceBatchCompute.hx, src/haxe/ccc/compute/client/cli/CliMain.hx
- Improve documentation for the command "ccc job status --help"
=> CLI doc improvement.

bin/run-stack-remote, bin/sync-to-remote, etc/config/serverconfig.template.yaml, src/haxe/ccc/compute/ComputeQueue.hx, src/haxe/ccc/compute/Definitions.hx, src/haxe/ccc/compute/InstancePool.hx, src/haxe/ccc/compute/ServiceBatchCompute.hx, src/haxe/ccc/compute/server/ServerCommands.hx, src/haxe/ccc/compute/server/tests/ServiceTests.hx, src/haxe/util/DateFormatTools.hx
New API: /api/rpc/status returns a json blob of jobs pending, jobs running on machines, and job finish state
=> New API: /api/rpc/status returns status on all jobs and workers

README.md, package.json, src/haxe/ccc/compute/ServiceBatchCompute.hx, src/haxe/ccc/compute/execution/DockerJobTools.hx, src/haxe/ccc/compute/server/ServerCompute.hx, src/haxe/ccc/compute/server/tests/ServiceTests.hx, src/haxe/ccc/compute/server/tests/TestJobs.hx, src/haxe/ccc/compute/server/tests/TestStoragePkgCloud.hx, src/haxe/ccc/compute/workers/WorkerProviderPkgCloud.hx, src/haxe/ccc/compute/workers/WorkerProviderTools.hx, src/haxe/ccc/storage/ServiceStorage.hx, src/haxe/ccc/storage/ServiceStorageBase.hx, src/haxe/ccc/storage/ServiceStorageLocalFileSystem.hx, src/haxe/ccc/storage/ServiceStoragePkgCloud.hx, src/haxe/ccc/storage/ServiceStorageS3.hx, src/haxe/ccc/storage/ServiceStorageSftp.hx, src/haxe/ccc/storage/StorageSourceType.hx, src/haxe/ccc/storage/StorageTools.hx, src/haxe/cloud/MachineMonitor.hx, src/haxe/js/npm/aws/AWS.hx, src/haxe/promhx/PollStreams.hx, src/haxe/util/DockerTools.hx, test/src/TestsIntegration.hx
S3 storage, refactored to use the official SDK, with S3 tests and integration tests
=> S3 storage, with full test integration.

src/haxe/ccc/compute/execution/BatchComputeDocker.hx, src/haxe/ccc/compute/execution/Job.hx, src/haxe/ccc/compute/server/ServerCommands.hx, src/haxe/cloud/MachineMonitor.hx
If a job fails, check a worker for disk space, if none, requeue the job instead of failing it.
=> If a job fails, check a worker for disk space.

src/haxe/ccc/compute/server/ServerCommands.hx, src/haxe/ccc/compute/server/tests/TestWorkerMonitoring.hx, src/haxe/ccc/storage/ServiceStorageS3.hx
- Fix worker monitoring test
- S3 file transfer where there is no file data
=> Fix worker monitoring test, and S3 file transfer

docker-compose.dev-server.yml, etc/hxml/cli-build.hxml, src/haxe/ccc/compute/Constants.hx, src/haxe/ccc/compute/Definitions.hx, src/haxe/ccc/compute/ServiceBatchCompute.hx, src/haxe/ccc/compute/client/ClientTools.hx, src/haxe/ccc/compute/client/cli/ClientCommands.hx, src/haxe/ccc/compute/execution/BatchComputeDocker.hx, src/haxe/ccc/compute/execution/Job.hx, src/haxe/ccc/compute/server/ServerCompute.hx, src/haxe/ccc/compute/server/tests/ServiceTests.hx, src/haxe/ccc/compute/server/tests/TestCompute.hx, src/haxe/ccc/compute/server/tests/TestJobs.hx, test/src/utils/TestTools.hx
- Job submission now can wait until the job is finished before returning the request.
=> Job submission now can wait until the job is finished before returning.

README.md, src/haxe/ccc/compute/execution/BatchComputeDocker.hx, src/haxe/ccc/docker/dataxfer/DockerDataTools.hx, src/haxe/ccc/docker/dataxfer/TestDataTransfer.hx, src/haxe/ccc/storage/ServiceStorage.hx, src/haxe/ccc/storage/ServiceStorageBase.hx, src/haxe/ccc/storage/ServiceStorageS3.hx, src/haxe/ccc/storage/StorageDefinition.hx
Add extra parameters to the S3 copy command for e.g. setting mime types when uploading.
=> Add extra parameters to the S3 copy command

bin/build-docker-images, bin/compile, bin/run-stack-remote-dev, docker-compose.dev-server.yml, package.json, src/haxe/ccc/compute/InstancePool.hx, src/haxe/ccc/compute/ServiceBatchCompute.hx, src/haxe/ccc/compute/execution/BatchComputeDocker.hx, src/haxe/ccc/compute/execution/DockerJobTools.hx, src/haxe/ccc/compute/server/ServerCommands.hx, src/haxe/ccc/compute/server/ServerCompute.hx, src/haxe/ccc/compute/server/tests/TestWorkerMonitoring.hx, src/haxe/ccc/compute/workers/WorkerProviderBase.hx, src/haxe/ccc/compute/workers/WorkerProviderPkgCloud.hx, src/haxe/promhx/CallbackPromise.hx, src/haxe/promhx/RedisPromises.hx, src/haxe/util/DateFormatTools.hx
=> Fixed crash (unhandled promise error) and add extra worker monitoring

bin/run-stack-remote-dev, docker-compose.core.yml, docker-compose.dev-server-remote.yml, src/haxe/ccc/compute/ServiceBatchCompute.hx, src/haxe/ccc/compute/execution/BatchComputeDocker.hx, src/haxe/ccc/compute/execution/Job.hx, src/haxe/ccc/compute/server/ServerCompute.hx, src/haxe/ccc/compute/server/tests/ServiceTests.hx, src/haxe/ccc/compute/server/tests/TestWorkerMonitoring.hx, src/haxe/ccc/compute/workers/WorkerProviderTools.hx, src/haxe/cloud/MachineMonitor.hx, src/haxe/promhx/HttpStreams.hx, src/haxe/util/DockerTools.hx
=> Fixed worker monitoring issue

README.md, etc/client/js/package.json, src/haxe/ccc/compute/client/js/ClientJS.hx, src/haxe/ccc/compute/server/ServerCompute.hx, src/haxe/ccc/compute/server/ServiceBatchCompute.hx, src/haxe/ccc/compute/shared/Constants.hx
See README.md for full documentation. New env vars:
LOG_LEVEL
REMOVE_JOBS_ON_STARTUP
DISABLE_STARTUP_TEST
=> Added new env var startup parameters

etc/bionano/README.md, src/haxe/ccc/compute/server/execution/BatchComputeDockerTurbo.hx, src/haxe/ccc/compute/server/execution/routes/ServiceBatchComputeTools.hx, src/haxe/ccc/compute/server/job/TurboJobs.hx, src/haxe/ccc/compute/server/tests/TestTurboJobs.hx, src/haxe/ccc/compute/shared/Definitions.hx
Fixes #126 follow up
- Turbo job containers removed after job completion
- Functional test checks the turbo job entry added and removed from redis
=> 126 follow up clean containers and redis

etc/bionano/README.md, etc/bionano/aws/cloudformation/lambda-autoscaling/cf-ccc-scaling.json, etc/bionano/aws/cloudformation/lambda-autoscaling/deploy, etc/bionano/aws/cloudformation/lambda-autoscaling/src/index.js, etc/bionano/aws/cloudformation/redis/deploy, etc/bionano/aws/cloudformation/servers/deploy, etc/bionano/aws/docker/docker-compose-aws.yml
=> BNR_ENV_TAG -> BNR_ENVIRONMENT

src/haxe/ccc/compute/server/execution/BatchComputeDocker.hx, src/haxe/ccc/compute/server/execution/routes/JobCommands.hx, src/haxe/ccc/compute/server/execution/routes/RpcRoutes.hx, src/haxe/ccc/compute/server/execution/singleworker/ProcessQueue.hx, src/haxe/ccc/compute/server/job/state/JobStateTools.hx, src/haxe/ccc/compute/server/tests/ServerTestTools.hx, src/haxe/ccc/compute/server/tests/TestCompute.hx, src/haxe/ccc/compute/server/tests/TestFailureConditions.hx, src/haxe/ccc/compute/server/tests/TestJobs.hx
- Revert job status API to original (need versioning)
- Temporarily disable timeout (they do not work)
=> Revert job status API to original (need versioning )

src/haxe/ccc/compute/server/execution/singleworker/ProcessQueue.hx
http://search-dev-bionano-es-search-2-sr7xpo4hkguqhtkemi55zefmb4.us-west-2.es.amazonaws.com/_plugin/kibana/#/discover?_g=(refreshInterval:(display:Off,pause:!f,section:0,value:0),time:(from:now-30d,mode:quick,to:now))&_a=(columns:!(_source),index:'logstash-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'name:ccc_server%20AND%20H1h3AbxiCg')),sort:!('@timestamp',desc))
When a job finishes, but there's an issue later on, for some reason it's not removed from the queue, even if the job otherwise finishes successfully. Adding an enum for this case, and handling it there. It doesn't address how the job got into the state to begin with.
=> Check for missing job definitions, and remove from queue if so

etc/client/js/package.json, src/haxe/ccc/compute/server/execution/BatchComputeDockerTurbo.hx, src/haxe/ccc/compute/server/execution/routes/RpcRoutes.hx, src/haxe/ccc/compute/server/execution/routes/ServiceBatchComputeTools.hx, src/haxe/ccc/compute/server/tests/TestTurboJobs.hx, src/haxe/ccc/compute/shared/Definitions.hx, src/haxe/ccc/docker/dataxfer/DockerDataTools.hx
New turbo jobs route with input/output encoding handling.
In other words, do not assume utf8 text
=> New turbo jobs route with input/output encoding handling.
